title: Stock Analysis Tool
description: Professional-grade stock analysis platform
theme: jekyll-theme-cayman

# Replace YOURUSERNAME with your actual GitHub username
baseurl: "/Test-with-AI"
url: "https://sanyamverma123.github.io"

# Enable GitHub Pages
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

github:
  is_project_page: true
  repository_url: "https://github.com/sanyamverma123/Test-with-AI"

# Navigation
nav_links:
  - title: Features
    url: "#features"
  - title: Documentation
    url: "/docs"
  - title: GitHub
    url: "https://github.com/yourusername/Test-with-AI"
